### ISSUE TITLE
Repo Yapisi Tasarimi

### ISSUE THREAD

**Issue by tarikguney** [gelis-tr-io/makaleler#1]
Tesekkurler @selmansamet yeni repo icin. Tasarim hakkinda topluluk uyeleri fikirlerini burada paylasabilirler.

**Comment by oktaysenkan** [comment]
Repo pinlenirse daha iyi olacağını düşünüyorum. @tarikguney

**Comment by tarikguney** [comment]
Repo tasarimi olarak soyle olabilir:

Teknolojiler birer klasor ve iclerinde ise haklarinda yazilmis makaleleler. Mesela:
```
- dotnet:
  - readme.md // dotnet ile alakali tum makallelerin listelendigi ve kimler tarafindan yazildigini iceren markdown dosyasi
  - task-kullanarak-parallel-islemler-yaptirma.md
  - task-mi-thread-mi-kullanmak-daha-mantikli.md
- php
   - readme.md // Tum makaleleri ve kimlerin yazdiginin listelendigi markdown dosyasi
   - PHP-de-MD5-hashing-sorunlari-ve-cozumleri.md
   - PHP-ve-Hack-karsilastirmasi.md
```

Bunlarin insanlara ulastirildigi kisim ise `readme.md` dosyasi olsun. Tabi zamanla `readme.md` dosyasinin cok buyume ve daha karmasik olma hali olacak. Onun icin duruma gore readme.md  dosyasinda her kategori altinda en son yayinlanan bir kisim makaleler olur ve gerisi ise, tum makaleleri gor gibi bir link yardimi ile `dotnet`, `php`, gibi klasorlerin icinde ki `readme.md` dosyalarina yonlendirilir.

**Comment by hurata** [comment]
> Repo tasarimi olarak soyle olabilir:
> 
> Teknolojiler birer klasor ve iclerinde ise haklarinda yazilmis makaleleler. Mesela:
> 
> ```
> - dotnet:
>   - readme.md // dotnet ile alakali tum makallelerin listelendigi ve kimler tarafindan yazildigini iceren markdown dosyasi
>   - task-kullanarak-parallel-islemler-yaptirma.md
>   - task-mi-thread-mi-kullanmak-daha-mantikli.md
> - php
>    - readme.md // Tum makaleleri ve kimlerin yazdiginin listelendigi markdown dosyasi
>    - PHP-de-MD5-hashing-sorunlari-ve-cozumleri.md
>    - PHP-ve-Hack-karsilastirmasi.md
> ```
> Bunlarin insanlara ulastirildigi kisim ise `readme.md` dosyasi olsun. Tabi zamanla `readme.md` dosyasinin cok buyume ve daha karmasik olma hali olacak. Onun icin duruma gore readme.md dosyasinda her kategori altinda en son yayinlanan bir kisim makaleler olur ve gerisi ise, tum makaleleri gor gibi bir link yardimi ile `dotnet`, `php`, gibi klasorlerin icinde ki `readme.md` dosyalarina yonlendirilir.

Bana gayet mantıklı geldi. Extra bir şey gelirse  aklıma burayı editleyeceğim.
Edit: Tüm makalelerin bir yerde listelenmesine pekte gerek yok gibi  o repoda find  file  yaparak aradığımız konuda makale var mı yok mu rahatlıkla görürüz.

**Comment by tarikguney** [comment]
Dosya isimlerinin sadece ingilizce karakter kabul etmesi Find File durumunu biraz karmasik hale getirebilir.

**Comment by oktaysenkan** [comment]
Dosya ve klasör isimleri hakkında bir name convention belirlersek daha iyi olacağını düşünüyorum.
`Android-Veri-Tipleri.md`, `android-veri-tipleri.md` ya da dosya hali hazırda **Android** klasörü altında olduğunu için direkt olarak `veri-tipleri.md` olabilir. Klasör isimleri ise `JavaScript`, `Javascript`, `javascript` olabilir diye düşünüyorum. Sizce ne olmalı ?

**Comment by tarikguney** [comment]
@oktaysenkan Command line ile dosya isimlerini yazdigim zaman en cok zorlandigim ve hizimi dusuren seylerden bir tanesi de birden fazla tusa basmak zorunda kalmak. Dolayisiyla, Shift'e basip bir karakteri buyuk harf yapmak ozellikle de makale gibi uzun dosya isimlerine sahip dosyalarda sorun oluyor. Bence tum isimler kucuk harfler ile baslasin ve bosluklar yerine `-` kullanilsin. Bosluk yani space kullanmak maalesef dosya isimlerinin escape edilmesine neden olabiliyor. Genelde `-` yerine `_` de kullananlar oluyor ama bunun icin de Shift tusuna basmak gerekiyor ki extra is demek.

Yukarida ki aciklmaya ornek olarak: `async-await-kullanimini-anlamak.md`.

Dosyalarin ismi icerisinde Javascript vs. gibi klasorden gelen isimlerin olup olmamasi ile alakali duruma gelince, tavsiyen bence mantikli. Tekrarlardan kacinmak guzel duruyor. Ama bunu yaparken de dosya isimlerinin anlasilir olup olmamasina bakmak lazim. Mesela: `async-await-kullanimi.md` gibi bir dosya ismi, icinde bulundugu klasore bakildiginda meselenin JS icinde anlatildigini gostermesi acisindan anlasilir duruyor. Ama mesela `numeric-degerlerin-javascripteki-karsiligi.md` seklinde bir dosya olusturmak zorunda kaldigimizda bunu `numeric-degerlerin-karsiligi.md` seklinde yazmak manayi dusuruyor. Bence burada ki isimleme icin kesin bir kural olmasina gerek yok, sadece anlasilir olsun yeter. Tek kural kullanilan karakter buyuklukleri ve space yerine `-` kullanmak olsun, o da insanlarin command line ortamlarinda bu dosyalarin isimlerini rahatlikla girebilmeleri icin.

**Comment by tarikguney** [comment]
Hatta ayni isimlendirme mantigi folder (klasorler) icin de olabilir. Insanlarin cogu git kullanirken bunu command line uzerinde kullaniyor. Insanlar ne kadar rahatlikla dosya ve klasor isimlerine ulasirlarsa, o kadar kolay olur onlar icin. Bu belki de yazilimcilarini normal kullanicilardan ayiran bir taraf. Yani pratik olmak ile anlasilir olmanin dengeli olmasi durumu. Normal insanlra genelde, anlasilir ve guzel durmasinin, pratik olmanin onune fazlasiyla koyabiliyorlar.

**Comment by sametcodes** [comment]
Yazılarda bulunacak olan görsel dosyalarını da dizinleme içerisinde düşünmemiz gerekiyor.

Örneğin `javascript/es6-semboller.md` şeklinde değil `javascript/es6-semboller/es6-semboller.md` olarak dizinlemeliyiz ki yazıyla ilgili görseller de `javascript/es6-semboller/` altında yer alabilsin. Doğrudan ilgili olduğu konunun dizini altında da bulunabilir görsel, fakat bir süre sonra dizin karışıklığından düzenleme yapmak zorlaşabilir.

Veya görseller için kök dizinde ayrı bir dizin mi açmalıyız?

**Comment by tarikguney** [comment]
Dediğin çok mantıklı. Ortak bir dizin üzerinde çalışmak merge conflict oluşturma sorununu arttırma durumu olabilir ve insanlar farkında olmadan başka resimleri silebilirler, vs. Dediğin gibi her makalenin kendi dizininin olması daha mantıklı. Bu şekilde düzenleyebilirsen, `master` içinde merge edebiliriz.

**Comment by oktaysenkan** [comment]
`javascript/es6-semboller/es6-semboller.md` yerine `javascript/es6-semboller/README.md` olması daha mantıklı olmaz mı ? klasöre girdiğimizde direkt olarak dökümanı okuyabiliriz.

**Comment by sametcodes** [comment]
@oktaysenkan [PR](https://github.com/gelis-tr-io/makaleler/pull/7)'da açıklamıştım.

> Makale dizini altında makalenin bulunduğu dosya adını değiştirmedim. Github'ta görüntüleme için README.md olarak adlandırmak daha kullanışlı olabilirdi, fakat dosya aramaları yapıldığı zaman karışıklık yaşanabileceğinden dosya adlarında değişiklik yapmadım
