### ISSUE TITLE
İçerik için ayırdığınız vakit

### ISSUE THREAD

**Issue by cihangll** [gelis-tr-io/makaleler#33]
Herkese selam. 
İçerik yazarken harcadığınız vakit nedir? Ortalama kaç saat harcıyorsunuz? Benim çok vaktimi aldığı için yazmamayı düşünüyorum. Fikrinizi, deneyimlerinizi bu issue altında paylaşır mısınız.

**Comment by sametcodes** [comment]
Selamlar.

Bazı yazı içeriklerine 3-4 saat harcadığım oluyor. Video olarak da üretince bu sayı artıyor.

Yeni bir yazı yazmanın amacını iyi belirlemek gerekiyor. Ben genelde hazırladığım makaleleri bir yandan kendim öğrenirken yazıyordum. Dolayısıyla yazma süreci zamana yayılıyordu ve pek vakit kaybı olduğunu düşünmüyordum. Zaten yeni bir şey öğrenmiş olma motivasyonu sürekliliği sağlıyordu.

Geri dönüşleri önemli olduğunu düşünüyorum. Video olarak ürettiğim içerikler için pek geri dönüş alamasam da ES6 ile ilgili hazırladığım bir kaç yazı için (bu repoda hepsi yok) aldığım geri dönüşler devam etmemi sağlamıştı. Bunun için yazının yayın hakkı bende olduğundan yayınlayabildiğim platformlarda ([kodcular medium](https://medium.com/kodcular), kendi blogum ve bir kaç blog daha) yazımı paylaşmıştım. Bu da geri dönüşlerin sayısını artırmıştı.

Özellikle spesifik bir konuda yazı hazırlıyorsan geri dönüşleri pek umursamamalısın. O konu seni her ne kadar cezbetse de bir başkası için ilgi çekici olmayabilir. Bunun motivasyonunu etkilemesine izin vermemelisin.

Son bir şey: hiçbir zaman aktif olarak sürekli yazamazsın. Eğer sürekli olarak öğreniyorsan bu bir miktar mümkün olabilir ama zamanını fazla alıyorsa tekrar düşünmen gerekir.

**Benim makale yazma konusunda getirdiğim bir çözüm şu**: eğer yazacağım konuyla ilgili Türkçe olarak bir içerik bulunmuyorsa o içeriği üretmeliyim. Eğer zaten varsa öyle bir kaynak üretmem çok elzem değil, insanlar zaten var olan kaynaktan faydalanabilir. Belki yazmayı bırakmak yerine "bu daha önce bir yerde yazılmış mı, bununla ilgili paylaşımlar var mı" diye araştırarak yazıp yazmamaya karar verebilirsin. Bunun etkili bir çözüm olduğunu düşünüyorum.

Umarım düşüncelerim faydalı olmuştur :)

**Comment by cihangll** [comment]
@selmansamet Selam. Vakit ayırıp fikrini ve tecrübeni paylaştığın için teşekkürler.
