### ISSUE TITLE
PHP Eğitimleri Serisi

### ISSUE THREAD

**Issue by hurata** [gelis-tr-io/makaleler#6]
Selamlar,
Özellikle yeni mezun arkadaşlar için düşünüyorum. Ama piyasada muadilleri var. Bundan dolayı fikirlerinizi alayım dedim. Acaba bu platformda katkılar sağlanarak ve sorun-çözüm odaklı bir seri haline getirirsek diğer muadillerine göre bir fark kazandırmış olur muyuz ?

Mesela görev dağılımları yaparak proje gerçekleştirilebilir bu şekilde bir fark yaratmış olabiliriz.

Böyle bir seriyi daha sağlıklı ve güçlü hale  getirmek için fikirlerinizi bekliyorum.

**Comment by tarikguney** [comment]
@hurata, önerin çok hoşuma gitti doğrusunu söylemek gerekirse. Burasının diğer yerlerden farkı herkesin katılım sağlayabilmesi. Dolayısıyla, onlarca insanın katkı sağlayabileceği bir yer benzer çalışmalardan çok daha farklı olmaya başlayacaktır. 

Çözüm odaklı deyince benim aklıma cookbook tarzında bir yer geldi. Yani soru ve cevap şeklinde ilerleyen bir yer. Mesela:

1. PHP ile dosyaların içeriği nasıl okunur?
2. PHP ile klasörlerin silinmesi. 
3. ...

Şeklinde insanların günlük hayatta devamlı ihtiyaç duyacağı ve yeni öğrenenlerin ise direk örnek kodlar üzerinden PHP öğrenebilecekleri bir kısım da bu eğitim serisinde olabilir.  Eğer bu sana daha mantıklı geldiyse, eğitim serisini direk cookbook halinde yapabilirsin. Kodları üzerinde de insanların kafalarının karışabileceği yerlerde ufak notlar düşebilir ve öğrendiklerinin pekişmesini sağlayabilirsin.

Cookbook şeklinde olsun olması, PHP eğitim serisi farklı bir repo içinde olması bana daha mantıklı geliyor. Çünkü içerisinde örnek kodlar, resimler, makaleler, vs. olacak şekilde komple bir seri olacağından diğer repoların içinde kaybolmasın. Eğer böyle bir şeyin öncülüğünü yapmak istersen, yeni bir repo oluşturmak ile başlayabilirsin. Bence çok güzel bir proje olabilir. Zaten buranın amaçlarından bir taneside bu.

**Comment by tarikguney** [comment]
Tanıdığın ve böyle bir proje içinde ileride populeritesinin çok daha artması muhtemel bir grup içinde böyle bir çalışmaya imza atmak isteyen arkadaşların varsa, onları da ekleyebilirim.

**Comment by hurata** [comment]
@tarikguney önerilerin için çok teşekkürler hocam.  Önerin gayet mantıklı geldi. Ek olarak Juniorlar arasında proje geliştirme takımı da kurmayı düşünüyorum eğitim serilerinden öğrenirken diğer taraftan öğrendiklerini uygulayabilecekleri bir projede olur bu sayede "Bir şeyler geliştireceğim ama proje bulmada zorlanıyorum." olayını da halletmiş oluruz.

**Comment by hurata** [comment]
tanııklarıma prıjeden bahsedeceğim.

**Comment by tarikguney** [comment]
Eger bu konu hakkinda daha fazla yorum yoksa, kapatiyorum. Konuya birseyler eklemek isteyen arkadaslar cikarsa, yeniden acilabilir yada yeni bir issue altinda buna referans verilerek devam edilebilir.
